export enum ROUTE {
  HOME = "/",
  SEARCH = "/search",
  CONTENT = "/content",
  SIGN_IN = "/sign-in",
  SIGN_UP = "/sign-up",
  NOT_FOUND = "*",
  RESET_PASSWORD = "/reset-password",
  ARTICLES = "/articles",
  ATRICLES_DETAILS = "/articles/:id",
  ARTICLES_PAGES = "/articles/:page",
  SEARCH_ARTICLES = "/articles/:title_contains",
  NEWS = "/news",
  NEWS_DETAILS = "/blogs/:id",
  NEWS_PAGES = "/blogs/:page",
  SEARCH_NEWS = "/blogs/:title_contains",
  ACCOUNT = "/account",
}
